import type { Detector } from '@guardrails/shared';
import { makeRegexDetectors, type RegexRule } from './factory.js';

/**
 * Provider-specific detectors. Each rule targets a documented key format so it
 * fires with high confidence and few false positives. Add new providers here —
 * that is all it takes to teach Guardrails a new key shape.
 */
export const providerRules: readonly RegexRule[] = [
  {
    id: 'openai-api-key',
    title: 'OpenAI API key',
    category: 'api-key',
    severity: 'critical',
    confidence: 'high',
    // `sk-...` and `sk-proj-...`, but not Anthropic's `sk-ant-...`.
    pattern: /sk-(?!ant-)(?:proj-)?[A-Za-z0-9_-]{20,}/,
    explanationId: 'openai-api-key',
  },
  {
    id: 'anthropic-api-key',
    title: 'Anthropic API key',
    category: 'api-key',
    severity: 'critical',
    confidence: 'high',
    pattern: /sk-ant-[A-Za-z0-9_-]{20,}/,
    explanationId: 'anthropic-api-key',
  },
  {
    id: 'aws-access-key-id',
    title: 'AWS access key ID',
    category: 'cloud-credentials',
    severity: 'critical',
    confidence: 'high',
    pattern: /A(?:KIA|SIA|GPA|IDA|ROA|IPA|NPA|NVA)[0-9A-Z]{16}/,
    explanationId: 'aws-access-key',
  },
  {
    id: 'aws-secret-access-key',
    title: 'AWS secret access key',
    category: 'cloud-credentials',
    severity: 'critical',
    confidence: 'high',
    boundary: false,
    pattern: /aws_secret_access_key\s*[=:]\s*["']?([A-Za-z0-9/+]{40})/i,
    group: 1,
    explanationId: 'aws-secret-key',
  },
  {
    id: 'github-token',
    title: 'GitHub token',
    category: 'token',
    severity: 'critical',
    confidence: 'high',
    pattern: /gh[pousr]_[A-Za-z0-9]{36}/,
    explanationId: 'github-token',
  },
  {
    id: 'github-fine-grained-pat',
    title: 'GitHub fine-grained personal access token',
    category: 'token',
    severity: 'critical',
    confidence: 'high',
    pattern: /github_pat_[A-Za-z0-9_]{22,}/,
    explanationId: 'github-token',
  },
  {
    id: 'gitlab-token',
    title: 'GitLab personal access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /glpat-[A-Za-z0-9_-]{20,}/,
    explanationId: 'gitlab-token',
  },
  {
    id: 'stripe-live-key',
    title: 'Stripe live secret key',
    category: 'api-key',
    severity: 'critical',
    confidence: 'high',
    pattern: /(?:sk|rk)_live_[A-Za-z0-9]{20,}/,
    explanationId: 'stripe-key',
  },
  {
    id: 'stripe-test-key',
    title: 'Stripe test secret key',
    category: 'api-key',
    severity: 'medium',
    confidence: 'high',
    pattern: /(?:sk|rk)_test_[A-Za-z0-9]{20,}/,
    explanationId: 'stripe-key',
  },
  {
    id: 'slack-token',
    title: 'Slack token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /xox[baprs]-[A-Za-z0-9-]{10,72}/,
    explanationId: 'slack-token',
  },
  {
    id: 'slack-webhook',
    title: 'Slack incoming webhook URL',
    category: 'token',
    severity: 'medium',
    confidence: 'high',
    boundary: false,
    pattern:
      /https:\/\/hooks\.slack\.com\/services\/T[A-Za-z0-9_]+\/B[A-Za-z0-9_]+\/[A-Za-z0-9]{16,}/,
    explanationId: 'slack-webhook',
  },
  {
    id: 'google-api-key',
    title: 'Google API key',
    category: 'api-key',
    severity: 'high',
    confidence: 'high',
    pattern: /AIza[0-9A-Za-z_-]{35}/,
    explanationId: 'google-api-key',
  },
  {
    id: 'google-oauth-secret',
    title: 'Google OAuth client secret',
    category: 'oauth',
    severity: 'high',
    confidence: 'high',
    pattern: /GOCSPX-[A-Za-z0-9_-]{28}/,
    explanationId: 'google-oauth',
  },
  {
    id: 'sendgrid-key',
    title: 'SendGrid API key',
    category: 'api-key',
    severity: 'high',
    confidence: 'high',
    pattern: /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/,
    explanationId: 'sendgrid-key',
  },
  {
    id: 'twilio-account-sid',
    title: 'Twilio account SID',
    category: 'token',
    severity: 'medium',
    confidence: 'medium',
    pattern: /AC[a-f0-9]{32}/,
    explanationId: 'twilio',
  },
  {
    id: 'twilio-api-key',
    title: 'Twilio API key SID',
    category: 'token',
    severity: 'medium',
    confidence: 'medium',
    pattern: /SK[a-f0-9]{32}/,
    explanationId: 'twilio',
  },
  {
    id: 'mailgun-key',
    title: 'Mailgun API key',
    category: 'api-key',
    severity: 'medium',
    confidence: 'medium',
    pattern: /key-[0-9a-f]{32}/,
    explanationId: 'mailgun',
  },
  {
    id: 'npm-token',
    title: 'npm access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /npm_[A-Za-z0-9]{36}/,
    explanationId: 'npm-token',
  },
  {
    id: 'pypi-token',
    title: 'PyPI upload token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /pypi-AgEIcHlwaS[A-Za-z0-9_-]{50,}/,
    explanationId: 'pypi-token',
  },
  {
    id: 'digitalocean-token',
    title: 'DigitalOcean personal access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /dop_v1_[a-f0-9]{64}/,
    explanationId: 'digitalocean',
  },
  {
    id: 'doppler-token',
    title: 'Doppler service token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /dp\.pt\.[A-Za-z0-9]{40,44}/,
    explanationId: 'doppler',
  },
  {
    id: 'shopify-token',
    title: 'Shopify access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /shp(?:at|ss|ca|pa)_[a-fA-F0-9]{32}/,
    explanationId: 'shopify',
  },
  {
    id: 'square-token',
    title: 'Square access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /sq0atp-[A-Za-z0-9_-]{22}/,
    explanationId: 'square',
  },
  {
    id: 'huggingface-token',
    title: 'Hugging Face access token',
    category: 'token',
    severity: 'high',
    confidence: 'high',
    pattern: /hf_[A-Za-z0-9]{34,}/,
    explanationId: 'huggingface',
  },
  {
    id: 'telegram-bot-token',
    title: 'Telegram bot token',
    category: 'token',
    severity: 'medium',
    confidence: 'medium',
    pattern: /\d{8,10}:[A-Za-z0-9_-]{35}/,
    explanationId: 'telegram',
  },
  {
    id: 'age-secret-key',
    title: 'age encryption secret key',
    category: 'private-key',
    severity: 'high',
    confidence: 'high',
    pattern: /AGE-SECRET-KEY-1[0-9A-Z]{58}/,
    explanationId: 'age-key',
  },
  {
    id: 'bearer-token',
    title: 'Bearer token',
    category: 'token',
    severity: 'medium',
    confidence: 'medium',
    boundary: false,
    pattern: /\bBearer\s+([A-Za-z0-9\-._~+/]{20,}=*)/,
    group: 1,
    explanationId: 'bearer-token',
  },
];

export const providerDetectors: readonly Detector[] = makeRegexDetectors(providerRules);
